### PR TITLE
refactor: export the snackbar with an allert to the toast component

### PR DESCRIPTION
**Pull request by AleksanderSkubala**
Small refactor, pls review

### CODE REVIEW

**Comment by AleksanderSkubala** [comment]
I've merged the changes from  #21, tell does it look right?

**Comment by AleksanderSkubala** [comment]
@tripleadev/amnesty

**Review by AdamSiekierski — CHANGES_REQUESTED** [review]
@AleksanderSkubala Looks good! Also add the Toast to the `/components/letters/LetterForm`. Merge the `dev` into your branch locally, add the changes and push to the PR 🙂

**Comment by AleksanderSkubala** [comment]
👀

**Review by AdamSiekierski — APPROVED** [review]

**Pull request merged**
