### PR TITLE
Fix Excel stats export

### PR DESCRIPTION
**Pull request by AdamSiekierski**

### CODE REVIEW

**Comment by datejer** [comment]
image
The top 3 authors in the stats section seem to lack a value 🤔

**Comment by AdamSiekierski** [comment]
well, that's how you created those stats @datejer :P

**Comment by AdamSiekierski** [comment]
i feel that the key should be for example `top.1` and the value - `1A.11`

**Comment by AdamSiekierski** [comment]
...will fix that

**Comment by datejer** [comment]
No, the stats are supposed to also return a value of how many letters that author wrote:
image
That's how it looks in the API and how it generates them.

**Comment by datejer** [comment]
The issue might be that those values are Strings and not numbers so this part skips them instead of inserting: 
image

**Comment by AdamSiekierski** [comment]
Ohhh, you're right 😄

**Review by datejer — APPROVED** [review]
LGTM, let's get those stats to Mr. War Touch ASAP 😁 🚀

**Pull request merged**
